name: Build Frontend

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create missing tsconfig.node.json
        run: |
          cat > tsconfig.node.json << 'EOL'
          {
            "compilerOptions": {
              "composite": true,
              "skipLibCheck": true,
              "module": "ESNext",
              "moduleResolution": "bundler",
              "allowSyntheticDefaultImports": true,
              "strict": true,
              "moduleDetection": "force"
            },
            "include": [
              "vite.config.ts",
              "package.json"
            ]
          }
          EOL

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Fix HTML references (optional)
        run: |
          # 备份原文件
          cp index.html index.html.backup
          # 移除有问题的脚本引用或添加 type="module"
          sed -i 's|<script src="/custom/index.js">|<script src="/custom/index.js" type="module">|g' index.html || true

      - name: Build frontend
        run: pnpm run build-only

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/