name: Build Frontend

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies with npm
        run: |
          # 如果存在 package-lock.json 就使用 npm
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi

      - name: Create missing config files
        run: |
          # 创建 tsconfig.node.json
          cat > tsconfig.node.json << 'EOL'
{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
EOL

      - name: Build frontend with npm
        run: npm run build-only

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/